baseURL: ""
languageCode: en-us
title: Technology Malta
theme: [hugo-PaperMod]
builddrafts: true

params:
  homeInfoParams:
    Title: 'Hello Visitor'
    Content: 'Welcome to my website'
  socialIcons:
    - name: Facebook
      url: "https://www.facebook.com/profile.php?id=100010368526072"
    - name: GitHub
      url: "https://github.com/davidvd14"